name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  go-lint-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/go-capabilities
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-gomod-

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Go build
        run: go build -v ./...

      - name: Lint
        run: golangci-lint run --timeout=3m

  openapi-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate OpenAPI
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: openapi/go-capabilities.yaml
